title: Agriturismo Il Gattesco
baseurl: /
permalink: '/:title/'
palette: yellow
header:
  bg_img: images/header-bg.jpg
  has_nav: true
  has_social: true
  logo_img: images/logo.png
  tagline: Minimal and clean blog theme
  title: Il Gattesco
footer:
  content: Letizia and Family wish you all the best
  links: []
sass:
  indentWidth: 4
  precision: 10
  style: nested
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - ssg-build.sh
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
